data_root: '/lotterlab/datasets/'
csv_path: '/lotterlab/users/matteo/data/CheXpert/metadata.csv'
output_dir: "./output"
output_name: "evaluation-chex-graphs"
seed: 42
#number_of_samples: 1
results_path: "/lotterlab/users/matteo/code/recon_bias/output/evaluation-chex-csv_20250113_132918/evaluation-chex-csv_20250113_132918_chex_results.csv"
reconstruction: 
  models: 
    - network: "UNet"
      photon_count: 100000
      model_path: "/lotterlab/users/matteo/models/Noise/Chex/unet-chex-07_20250109_151718/checkpoints/unet-chex-07_20250109_151718_epoch_19_best.pth"
    - network: "UNet"
      photon_count: 10000
      model_path: "/lotterlab/users/matteo/models/Noise/Chex/unet-chex-06_20250109_151619/checkpoints/unet-chex-06_20250109_151619_epoch_20_best.pth"
    - network: "UNet"
      photon_count: 3000
      model_path: "/lotterlab/users/matteo/models/Noise/Chex/unet-chex-05_20250107_144825/checkpoints/unet-chex-05_20250107_144825_epoch_19_best.pth"
    - network: "GAN"
      photon_count: 100000
      model_path: "/lotterlab/users/matteo/models/Noise/Chex/Chex-07/5_net_G.pth"
    - network: "GAN"
      photon_count: 10000
      model_path: "/lotterlab/users/matteo/models/Noise/Chex/Chex-06/latest_net_G.pth"
    - network: "GAN"
      photon_count: 3000
      model_path: "/lotterlab/users/matteo/models/Noise/Chex/Chex-05/latest_net_G.pth"
classifier:
  model_path: "/lotterlab/users/matteo/code/torchxrayvision/output/class_norm01/chex-densenet-class_norm01-best.pt"


