output_dir: './output'
output_name: 'unet-chex-10000-fairness-001'
save_interval: 1
dataset: 'chex'

fairness_lambda: 0.01

num_epochs: 20
learning_rate: 0.0001
batch_size: 16
early_stopping_patience: 5

csv_path_A: /lotterlab/project_data/reconstruction_bias/CheXpert_noise/metadata_photon_10000.csv
csv_path_B: /lotterlab/users/matteo/data/CheXpert/metadata.csv
dataroot_A: /lotterlab/project_data/reconstruction_bias/CheXpert_noise
dataroot_B: /lotterlab/datasets/

network_type: 'UNet'
model_path: /lotterlab/users/matteo/models/Noise/Chex/unet-chex-05_20250107_144825/checkpoints/unet-chex-05_20250107_144825_epoch_20_final.pth
seed: 31415

classifier_path: /lotterlab/users/matteo/code/torchxrayvision/output/class_norm01/chex-densenet-class_norm01-best.pt
