output_dir: './output'
output_name: 'unet-chex'
save_interval: 1

num_epochs: 20
learning_rate: 0.0001
batch_size: 16
early_stopping_patience: 5

data_root: '../../data/CheXpert'
csv_path: '../../data/CheXpert/CheXpert_metdata.csv'
lower_slice: 60
upper_slice: 130
age_bins: [0, 58, 100]
photon_count: 3000

network_type: 'UNet'
seed: 31415
