output_dir: './output'
output_name: 'unet-fairness-chex-10000-adv-lambda-<lambda-name>'
save_interval: 5
dataset: 'chex'

fairness_lambda: <lambda>

num_epochs: 20
learning_rate: 0.0001
batch_size: 16
early_stopping_patience: 5

csv_path_A: /lotterlab/project_data/reconstruction_bias/CheXpert_noise/metadata_photon_10000.csv
csv_path_B: /lotterlab/users/matteo/data/CheXpert/metadata.csv
dataroot_A: /lotterlab/project_data/reconstruction_bias/CheXpert_noise
dataroot_B: /lotterlab/datasets/

network_type: 'UNet'
model_path: /lotterlab/users/matteo/models/Noise/Chex/unet-chex-10000_20250210_170539/checkpoints/unet-chex-10000_20250210_170539_epoch_20_best.pth
seed: 31415

classifier_path: /lotterlab/users/matteo/code/torchxrayvision/output/class_norm01/chex-densenet-class_norm01-best.pt
